### ISSUE TITLE
Support for modules

### ISSUE THREAD

**Issue by JulianBissekkou** [tappeddev/injector#24]

**Comment by jogboms** [comment]
Hey @JulianBissekkou 

How is this supposed to look?

**Comment by JulianBissekkou** [comment]
Not decided yet. Feel free to suggest an api/feature. 

We will support importing/replacing/deleting a module and/or a subgroup of dependencies.
Since I am a fan of kodein, it will probably have a similar syntax but we are open to new/other features as well!

https://kodein.org/Kodein-DI/index.html?latest/core#_modules

**Comment by stefanschaller** [comment]
Looks like there is no need
